---
version: 0.2

phases:
  install:
    commands:
      - yum update -y --skip-broken
      - yum -y install curl jq python3-pip python3-dev perl-Digest-SHA --skip-broken
      - pip3 install --upgrade awscli
      - export PATH=$PWD/:$PATH
      - curl -o go1.18.3.linux-amd64.tar.gz https://go.dev/dl/go1.18.3.linux-amd64.tar.gz -vvv -L
      - shasum -a 256 -c <<< '956f8507b302ab0bb747613695cdae10af99bbd39a90cae522b7c0302cc27245  go1.18.3.linux-amd64.tar.gz'
      - rm -rf /usr/local/go && tar -C /usr/local -xzf go1.18.3.linux-amd64.tar.gz
      - export PATH=/usr/local/go/bin:$PATH
      - go version
      - go install github.com/sigstore/cosign/cmd/cosign@latest

  pre_build:
    commands:
      - make ecr_auth
  build:
    commands:
      - make docker_build

  post_build:
    commands:
      - make docker_push
      - make key_gen
      - make sign
      - make verify
artifacts:
  files: build.json